"""Reviewed academic content shared by the editable and printable report."""

TITLE = "Haunted Toy Room: The Midnight Mission"
AUTHOR = "Adiba Tahsin"
ROLL = "2107031"
COURSE = "CSE-4102"
COURSE_NAME = "Computer Graphics and Image Processing Laboratory"
TEACHERS = ["Md Tajmilur Rahman, Lecturer", "Md Mubtashim Abrar Nihal, Lecturer"]

PROPOSAL = [
    ["A toy room becomes alive at night and quiet in the morning", "Seven mission scenes, arrival prologue, night-to-dawn clock and restored rest poses", "StoryDirector / PennyArrival / Environment"],
    ["Recognisable primitive-built toys", "Woody, Jessie, Bullseye, Buzz and RC car; Penny and a ghost", "Humanoid / Bullseye / RCCar / Cat"],
    ["At least four independently controlled objects", "Five driveable toys, controllable ball and lamp; click-based inspection", "Select / HandleObjectControl"],
    ["Jessie mounts and follows Bullseye", "Saddle reparenting, a smooth seat transition and world-space dismount", "Mount / Dismount / SceneNode"],
    ["Translation, rotation, scale and hierarchy", "TRS, shear, reflection, normal correction and parent-child motion", "Transform3D / Transform / SceneNode"],
    ["Lighting and shading", "Directional, point and spot lights; Flat, Gouraud, Phong and Blinn-Phong", "lighting.glsl / Renderer"],
    ["Moving environment", "Lamp swivel/flicker, rolling ball, ghost motion, ceiling fan and clock hands", "Environment / StepScene"],
    ["Texturing and bonus ray tracing", "22 mapped surfaces, own BMP loader, analytic GPU tracing with BVH, shadows and reflection", "Assets / ProceduralTextures / RayTracer"],
]

# Blocks: heading, paragraph, equation, figure, table, page. Figures are project screenshots or authored diagrams.
BLOCKS = []
def h(text, level=1): BLOCKS.append(("heading", text, level))
def p(text): BLOCKS.append(("paragraph", text))
def e(text): BLOCKS.append(("equation", text))
def f(name, caption): BLOCKS.append(("figure", name, caption))
def t(caption, headers, rows): BLOCKS.append(("table", caption, headers, rows))

h("Abstract", 0)
p("Haunted Toy Room: The Midnight Mission is an interactive three-dimensional graphics project in which a furnished toy room becomes the setting for a coordinated rescue story. Penny, a white cat with ginger patches, walks from the garden into a two-storey house and upstairs. At midnight Woody discovers a stranded car; Jessie rides Bullseye, Buzz clears a doorway obstacle with his laser, and the group escorts the car home. Morning lighting restores the toys to their resting poses.")
p("The implementation uses C++ and an OpenGL 3.3 core pipeline. Five indexed primitive families form the complete environment and articulated models. Hand-authored homogeneous transformations support a scene hierarchy, multiple camera modes and an object inspector. A shared illumination model supplies ambient, diffuse and specular terms for directional, point and spot lights. Flat, Gouraud, Phong and Blinn-Phong shading can be compared in the raster path. Procedural surface maps and a custom BMP loader provide texture detail. The optional GPU ray tracer intersects transformed analytic primitives through a median-split bounding volume hierarchy, then evaluates shadow rays, mirror reflection and straight-through transparency. The project combines cinematic playback, live character takeover and full manual control so each graphics concept can be demonstrated independently.")

h("CHAPTER I — Introduction")
h("1.1 Project background and motivation", 2)
p("A room of articulated toys provides a practical setting for explaining geometry, local coordinate systems, surface appearance and motion together. The visual narrative gives a purpose to each operation: a wheel rotates because a car moves, a rider follows because her root belongs to the saddle, and a spotlight follows a moving lamp head because its anchor belongs to that head. The haunted atmosphere is expressed through night colours, lamp flicker, a translucent ghost and self-moving props.")
f("room-night", "The furnished toy room under moonlight and the desk lamp. Furniture, curtains, the clock and ceiling fan establish the scale of the articulated toys.")
h("1.2 Objectives and scope", 2)
p("The objectives are to construct a complete scene from reusable indexed geometry; implement and demonstrate three-dimensional transformations; compare Gouraud and Phong shading; explain three light types through one illumination equation; animate articulated and rolling objects with elapsed time; provide keyboard and mouse interaction; and extend the renderer with analytic ray tracing. Modelling, shader logic, procedural textures, BMP parsing, story choreography and the interface are implemented within the project. GLFW provides window/input services, GLAD loads OpenGL entry points, and GLM supplies vector and matrix storage and algebra.")
h("1.3 Proposed features and final implementation", 2)
p("The recorded concept specifies a child's toy room that comes alive at night, primitive-built controllable characters, Jessie riding Bullseye through a parent-child hierarchy, and a morning return. The final implementation realises these features and adds a connected house, Penny's arrival, collision-aware movement, detailed textures and two rendering paths. Table 1 maps the proposed functionality to the corresponding final modules.")
t("Proposal-to-implementation coverage", ["Proposed functionality", "Final implementation", "Principal code"], PROPOSAL)
h("1.4 Project workflow and organisation", 2)
p("Geometry and material resources are created once. Scene builders assemble the room, house and characters from those resources. Each frame reads input, advances the story and motion, resolves physical contacts, propagates world transforms, refreshes lights and renders the selected graphics path. This report first establishes the theory, then explains the methodology and individual models, and finally presents visual comparisons, verification and the complete object inventory.")
f("pipeline-diagram", "One frame from input to the displayed image. Both rendering paths consume the same scene transforms, materials and lights.")

h("CHAPTER II — Graphics Foundations")
h("2.1 Indexed geometry and curved surfaces", 2)
p("A vertex stores three position coordinates, three normal coordinates and two texture coordinates. An index buffer groups vertices into triangles. A plane has four vertices and two triangles. A cube has 24 vertices rather than eight because a corner needs independent face normals and UV coordinates on each adjacent face. Shared primitive buffers reduce duplicated geometry while model matrices give each instance its dimensions and placement. The graphics pipeline and programmable stages are defined by the OpenGL specification [1].")
e("Vertex = (px, py, pz, nx, ny, nz, u, v); stride = 8 × 4 = 32 bytes\nTriangle k = indices[3k], indices[3k+1], indices[3k+2]")
t("Full-detail primitive meshes", ["Primitive", "Definition", "Vertices", "Triangles"], [
    ["Plane", "1 × 1 in XZ, normal +Y", "4", "2"],
    ["Cube", "[-0.5,0.5] on all axes", "24", "12"],
    ["Sphere", "radius 0.5; 24 stacks × 36 sectors", "925", "1656"],
    ["Cylinder", "radius 0.5, height 1, 32 sectors; two caps", "134", "128"],
    ["Cone", "base radius 0.5, height 1, 32 sectors; one cap", "99", "64"],
])
p("For the sphere, latitude phi ranges from -pi/2 to pi/2 and longitude theta from 0 to 2pi. A rectangular grid of (stacks+1)(sectors+1) vertices includes duplicated seam positions at u=0 and u=1. Adjacent cells create two triangles, except at the poles where a degenerate half is omitted. Analytic curved surfaces remain exact in the ray tracer; in raster mode their appearance also depends on tessellation and level of detail.")
e("Sphere: p = 0.5(cos(phi) sin(theta), sin(phi), cos(phi) cos(theta))\nn = 2p; u = theta/(2pi); v = phi/pi + 0.5\nSphere triangles = 2 × sectors × (stacks - 1)")
p("Cylinder sides use circular rings with outward radial normals; cap rings have independent +Y or -Y normals. Cone sides use a radial slope normal and a duplicated apex normal for each sector. Splitting these vertices keeps the cap edge sharp while allowing smooth curved side shading. Counter-clockwise triangles define the outside; mirrored instances reverse the front-face convention during raster drawing.")
e("Cylinder side: p = (0.5 sin(theta), y, 0.5 cos(theta)); n = (sin(theta),0,cos(theta))\nCone side: n = normalize(sin(theta), 0.5, cos(theta))\nCylinder vertices = 4n + 6; triangles = 4n\nCone vertices = 3n + 3; triangles = 2n")
f("primitive-diagram", "Five unit primitives and their main uses. Curved geometry is constructed by sampling angular parameters, then transformed into ellipsoids, wheels, limbs and lamp parts.")
f("wireframe", "Wireframe view of Buzz exposes the indexed triangles; cylinders and spheres form the limbs, head and helmet.")
p("A polygon is a closed face; the renderer submits triangles rather than general polygons. addQuad triangulates a counter-clockwise four-corner face into (a,b,c) and (c,d,a). For the plane, v0=(-0.5,0,0.5), v1=(0.5,0,0.5), v2=(0.5,0,-0.5), v3=(-0.5,0,-0.5); all normals are +Y and the UVs are (0,0),(1,0),(1,1),(0,1). Its six indices are 0,1,2,2,3,0. The cube repeats this construction with a different normal for each face: 24 vertices, 36 indices and 12 triangles. Cross(edge1,edge2) defines a face normal; counter-clockwise winding selects the front face.")
p("For a sphere ring i and sector j, k1=i(sectors+1)+j and k2=k1+sectors+1. The cell emits (k1,k2,k1+1), except at the top pole, and (k1+1,k2,k2+1), except at the bottom pole. With 24 stacks and 36 sectors this gives 925 vertices and 1656 triangles (4968 indices). A cylinder uses two side rings, duplicated cap rings and two centres; side quads become two triangles and each cap is a triangle fan. A cone uses a base side ring, sector-specific apex normals, a separate cap ring and a centre; each sector supplies one side triangle and one cap triangle. Seam duplication preserves both u=0 and u=1. The full vertex/index listings are in docs/03-primitives.md and can be printed with Shift+V.")
h("2.2 Homogeneous transformations", 2)
p("Points are column vectors (x,y,z,1); directions use w=0, so translation changes points without changing directions. Products act from right to left. A node's local matrix first scales its primitive, applies an optional basis matrix for accumulated rolling, shear or reflection, applies roll, pitch and yaw, and then translates it. Transform::Matrix evaluates the rotation entries directly to avoid repeated general matrix products.")
e("Mlocal = T(position) Ry(yaw) Rx(pitch) Rz(roll) B S(scale)\nT = [1 0 0 tx; 0 1 0 ty; 0 0 1 tz; 0 0 0 1]\nS = diag(sx,sy,sz,1)\nRy = [cos(a) 0 sin(a) 0; 0 1 0 0; -sin(a) 0 cos(a) 0; 0 0 0 1]")
p("Rotation about an arbitrary unit axis follows Rodrigues' construction. A pivot rotation moves the pivot to the origin, rotates, then restores it. A shear changes one coordinate in proportion to another; a reflection reverses the component along a plane normal. These are linear operations stored in B. They are visible in the inspector, while translation and Euler rotation remain individually editable.")
e("R(axis,a) = cos(a)I + (1-cos(a)) axis axis^T + sin(a)[axis]cross\nMpivot = T(pivot) R T(-pivot)\nShear example: x' = x + k y\nReflection about a plane through the origin: F = I - 2 n n^T")
h("2.3 Hierarchy and transformed normals", 2)
p("An empty scene node is a joint; a mesh-bearing node is a visible part. Descendants inherit their parent's world transform, so moving a shoulder rotates its complete arm. Non-uniform shape scale is normally placed on leaf nodes to preserve the proportions of sibling parts. Normals require the inverse transpose of the world linear matrix: transforming them as ordinary directions would break perpendicularity under non-uniform scale or shear.")
e("Mworld(child) = Mworld(parent) Mlocal(child)\nNworld = normalize((A^-1)^T Nobject), where A = mat3(Mworld)\n(A^-T n) · (A t) = n · t = 0 for a tangent t")
f("hierarchy-diagram", "Jessie as an independent root and as a child of Bullseye's saddle. The world-to-local conversion preserves placement before the seat transition.")
h("2.4 Camera, projection and picking", 2)
p("The camera constructs a forward vector from yaw and pitch, a right vector from forward cross global up, and an orthogonal up vector. The view matrix expresses world points in that frame. Perspective projection divides by depth to make distant objects smaller. Free, Orbit and Follow modes use the same view/projection equations; orbit changes eye position around a target, while field-of-view zoom changes the lens angle.")
e("f = normalize(target - eye); r = normalize(f × worldUp); u = r × f\nView rows = (r,-r·eye), (u,-u·eye), (-f,f·eye), (0,0,0,1)\nclip = P V M p; NDC = clip.xyz/clip.w\nP00 = 1/(aspect tan(fov/2)); P11 = 1/tan(fov/2)\nP22 = -(far+near)/(far-near); P23 = -2 far near/(far-near); P32 = -1")
p("For picking, a screen point is converted to normalised device coordinates and a camera ray. Each candidate's inverse model matrix maps that ray to object space. The nearest positive primitive intersection chooses the object's owner. Collision-aware camera movement and orbit sightline tests prevent the view from passing through furniture; the open doorway permits inspection in the connected hallway. GLFW supplies the event callbacks and input states [2].")
e("d = normalize(f + xNDC tan(fov/2) aspect r + yNDC tan(fov/2) u)\noObject = M^-1(oWorld,1); dObject = M^-1(dWorld,0)")
h("2.5 Illumination: ambient, diffuse and specular", 2)
p("The project uses the Phong reflection model [3] as a local surface model. At a visible surface point, N is the unit normal, L points toward the light and V toward the eye. The RGB albedo C is material colour multiplied by a texture sample. Ambient light supplies a constant scene term; diffuse light depends on the surface orientation; specular light depends on the viewing direction and shininess. Emissive E is added independently for a glowing bulb, laser or sky. Emission alone does not illuminate nearby surfaces, so a separate light is attached where that effect is required.")
e("I = C [ka Ia + Σ visibility_i attenuation_i cone_i Il_i kd max(N·L_i,0)]\n    + Σ visibility_i attenuation_i cone_i Il_i ks max(R_i·V,0)^n + E\nR = 2(N·L)N - L;  C = materialRGB × textureRGB")
p("Directional lights use parallel rays and unit attenuation. Point lights radiate from a position and diminish with distance. Spotlights add a cone factor between inner and outer half-angles. smoothstep gives a gradual cone edge; its arguments are cosine values, so the outer-angle cosine is the smaller bound. F5, F6 and F7 independently disable the ambient, diffuse and specular terms.")
e("Directional: L = normalize(-lightDirection), attenuation = 1\nPoint: L = (lightPosition-P)/d; attenuation = 1/(kc + kl d + kq d²)\nSpot: theta = (-L)·axis; cone = smoothstep(cos(outer),cos(inner),theta)\nsmoothstep = q²(3-2q), q = clamp((theta-cos(outer))/(cos(inner)-cos(outer)),0,1)")
f("lighting-diagram", "Directional, point and spot light geometry, followed by the normal, light, view and reflection vectors at a surface point.")
p("After sampling an RGB texel, albedo C is the componentwise product of that texel and the material tint. The shader adds C times ambient-plus-diffuse, then the untinted specular light colour and emission. For C=(0.4,0.6,0.8), ambient factor 0.06, diffuse factor 0.1791 and white specular factor 0.0277, RGB is (0.12334,0.17116,0.21898) before framebuffer storage. Texture alpha is used for cutout coverage; material opacity controls blending/transmission. These are componentwise shader values, not a physically calibrated spectral or tone-mapped pipeline.")
p("As a numerical example, with ka=0.2, Ia=0.3, kd=0.8, N·L=0.6, ks=0.4, R·V=0.9, n=16, d=4 and (kc,kl,kq)=(1,0.14,0.07), attenuation is 1/2.68 = 0.3731. For unit light intensity and full cone visibility, the scalar ambient, diffuse and specular factors are 0.06, 0.1791 and 0.0277. The coloured terms multiply C; the specular term remains in the light's colour. The implementation suppresses specular response when N dot L is nonpositive, so a light behind a surface cannot create a front-facing highlight. Increasing n narrows the highlight, while increasing kq reduces distant illumination.")
h("2.6 Shading techniques and interpolation", 2)
p("Illumination is the rule for light at one point; shading determines where that rule is evaluated across the surface. Gouraud evaluates lighting at vertices and interpolates it [4]. Phong interpolates normals and evaluates lighting per fragment [3]. The project's Flat mode uses a triangle face normal computed from derivatives of world position; its lighting can still vary within that face because point-light distance and the view vector vary. Blinn-Phong replaces the reflection-vector dot product with a half-vector term [5].")
t("Shading evaluation in the raster pipeline", ["Mode", "Normal / evaluation", "Characteristic"], [
    ["Flat", "Nface = normalize(dFdx(P) × dFdy(P)); lighting per fragment", "Planar facets remain visible"],
    ["Gouraud", "Lighting per vertex; ambient/diffuse and specular interpolated separately", "Narrow highlights between vertices can disappear"],
    ["Phong", "Interpolated N normalised per fragment; max(R·V,0)^n", "Smoother moving highlights on curved geometry"],
    ["Blinn-Phong", "H=normalize(L+V); max(N·H,0)^(4n)", "Half-vector highlights; 4n approximates similar width"],
])
e("Perspective-correct attribute = [Σ lambda_i attribute_i / w_i] / [Σ lambda_i / w_i]\nGouraud colour = C × interpolated(ambient+diffuse) + interpolated(specular) + E\nPhong normal = normalize(interpolated(vertexNormal))")
p("F2 cycles the raster modes and automatically selects raster rendering. The ray tracer shades analytic surface hits per pixel; it can use the Phong or Blinn specular equation, but it does not perform Gouraud triangle interpolation or display polygon facets. This distinction is necessary when explaining the comparison.")
h("2.7 Texture mapping and procedural detail", 2)
p("Each primitive stores UV coordinates. A material's uvScale repeats its pattern over the model. Cube faces have separate rectangular charts, sphere UVs follow longitude and latitude, and cylinder/cone sides wrap their angular coordinate while caps use planar coordinates. Multiplying texture RGB by material RGB allows the same wood or greyscale siding pattern to take several colours. The raster textures preserve their native dimensions; all 22 ray-traced maps are bilinearly resampled into 512 × 512 layers of one texture array.")
e("uvSample = uv × uvScale; repeated coordinate = fract(uvSample)\nBilinear sample = (1-a)(1-b) C00 + a(1-b) C10 + (1-a)b C01 + ab C11\nTrilinear filtering blends bilinear samples from two adjacent mip levels")
f("uv-diagram", "UV parameterisation and repeated surface detail. A duplicated seam separates u=0 from u=1 while keeping the same geometric position.")
p("Most maps are generated in CPU memory with deterministic arithmetic. Hash values select per-cell variations. Smooth value noise bilinearly interpolates four hashed grid samples after applying q²(3-2q) to each fractional coordinate. Layered noise supplies grain, woven variation and grass. These are colour patterns; they do not displace vertices or implement normal mapping. The poster is loaded from a 24-bit BMP file generated by tools/make_poster.py. The custom loader handles headers, padded rows, orientation and BGR-to-RGB conversion.")
e("BMP row stride = 4 ceil((width × bitsPerPixel)/32)\nPositive BMP height: bottom-up rows; negative height: top-down rows\nLoaded (B,G,R) is stored as (R,G,B,A=255)")
h("2.8 Visibility, shadows and ray tracing", 2)
p("The raster path creates a 2048 × 2048 depth map from the lamp spotlight. Each visible surface is projected into the lamp's clip space and compared with that depth. A nine-sample 3 × 3 percentage-closer filter softens the edge. A small normal-dependent bias limits self-shadow acne. This is a depth comparison technique, distinct from the ray tracer's visibility rays. Other raster lights have no general shadow maps; flattened translucent contact shapes supplement the toys' contact with the floor.")
e("shadowCoordinate = (LightVP × vec4(P,1)).xyz / w × 0.5 + 0.5\nbias = max(0.0009(1-max(N·L,0)),0.00012)\nvisibility = (1/9) Σ [receiverDepth-bias ≤ storedDepth]")
p("The optional tracer follows the primary/visibility/reflection structure associated with Whitted-style ray tracing [6]. A full-screen triangle launches one primary ray for each traced pixel. The shader finds the nearest analytic surface, shades it, tests selected shadow rays and continues along a reflected ray or a straight transmission ray. Bounces are bounded and throughput below 0.02 terminates the path. At the last permitted hit the tracer uses local illumination to close the finite path.")
e("Ray: P(t) = o + t d, t > epsilon\nSphere: (d·d)t² + 2(o·d)t + (o·o - 0.25) = 0\nCylinder side: (dx²+dz²)t² + 2(ox dx+oz dz)t + ox²+oz²-0.25 = 0\nCone: x²+z² = 0.25(0.5-y)², with -0.5 ≤ y ≤ 0.5\nPlane: t = -oy/dy, bounded by |x|,|z| ≤ 0.5\nCube slabs: tEnter = max(min(t0,t1)); tExit = min(max(t0,t1))")
p("Object-space ray directions are deliberately not normalised after applying the inverse model matrix. Therefore the parameter t is identical in world and object space, allowing comparisons among differently scaled instances. Sphere, cylinder and cone sides reduce to quadratic equations; cylinder/cone caps use disk tests. When a cone coefficient a is approximately zero, its equation becomes linear. A ray beginning inside a cube uses the exit slab intersection. One-sided planes respect the authored wall direction.")
e("Reflection: dNext = d - 2(d·N)N; originNext = P + 0.002 N\nCaccum += throughput × (1-rho) × Clocal; throughput *= rho\nTransmission: Caccum += throughput × opacity × Clocal\nthroughput *= (1-opacity); originNext = P + 0.002 d")
p("Transparency follows the existing ray direction; it does not bend according to an index of refraction. In this single continuation implementation, transparent surfaces use transmission before the opaque reflection branch; the ghost and helmet therefore demonstrate transparency, while the polished floor and ball demonstrate mirror reflection. The image is not a path-traced global-illumination solution: there are no diffuse secondary bounces, caustics or physically simulated area lights.")
p("The default ray budget is two continuations: the primary hit plus at most two further hits (three surface evaluations). Key 9 cycles 0 through 4, allowing at most five hit evaluations. The loop includes bounce zero and ends after uMaxBounces. A miss adds throughput times the background. At an opaque reflecting surface it adds throughput times (1-rho) times the local lit colour, then multiplies throughput by rho. A transparent hit instead adds throughput times alpha times local colour and continues straight with throughput times (1-alpha). The last permitted hit contributes its full local colour; the path also stops if its largest throughput component falls below 0.02. Visibility rays are extra occlusion queries, not additional colour bounces.")
e("Example: rho0=0.2, rho1=0.5; local colours C0=(0.6,0.3,0.1), C1=(0.2,0.4,0.8), C2=(0.1,0.1,0.2)\nTwo-continuation result = 0.8 C0 + 0.2(0.5 C1) + 0.1 C2 = (0.51,0.29,0.18)")
f("ray-diagram", "Primary, shadow, reflected and transmitted rays. A finite bounce budget limits tracing cost; the local surface model supplies each hit's colour.")
h("2.9 Bounding volume hierarchy and conservative bounds", 2)
p("A bounding volume hierarchy encloses groups of primitives with boxes, rejecting whole groups when a ray misses the box [7]. This project rebuilds a median-split tree over the visible scene each frame because its toys and doors move. The longest spread of box centres chooses the split axis; leaves contain at most two instances unless their centres coincide. Closest-hit traversal visits the nearer child first and prunes nodes farther than the current hit. Shadow traversal stops at the first qualifying opaque occluder.")
e("World AABB centre c = M[3].xyz\nHalf-size h = 0.5(|M[0].xyz| + |M[1].xyz| + |M[2].xyz|)\nNode bounds = union(child bounds)\nConservative sphere radius = 0.5 max over sy,sz in {-1,+1} |a0 + sy a1 + sz a2|")
p("The sphere-bound expression measures the four distinct lengths among the eight transformed cube corners and remains valid under shear. The earlier orthogonal-column expression is insufficient when axes cease to be perpendicular. Scene nodes that are not visible are omitted from drawing and tracing, but the ray scene is not camera-frustum culled: off-screen geometry can still be visible in a reflection or block a shadow ray.")
f("bvh-diagram", "A spatial hierarchy rejects groups of distant objects before exact primitive intersection. The bounds must enclose the geometry after rotation, scale and shear.")

h("CHAPTER III — Methodology and Object Construction")
h("3.1 Resource ownership and rendering architecture", 2)
p("Assets owns five full-detail primitive meshes, lower-detail curved meshes, textures and materials. SceneNode stores pointers to these resources and owns its children. GPU wrappers manage buffers, arrays, shaders and textures for their lifetimes. Renderer collects visible shapes into DrawItems with model and normal matrices. The raster path uses indexed draws; RayTracer packs inverse transforms, material coefficients and BVH nodes into an RGBA32F texture buffer. The same light equations are included by both shader paths through lighting.glsl.")
t("Module responsibilities", ["Module", "Responsibility", "Entry point"], [
    ["core", "Window, frame loop, elapsed time, input edges, asset paths", "Application::Run / Input"],
    ["geometry / math", "Primitive vertices and indices; matrices; CPU intersections", "Primitives / Transform3D / RayIntersect"],
    ["scene", "Local transforms, hierarchy, materials, camera and lights", "SceneNode::UpdateWorld"],
    ["characters", "Model assembly, drive state, gait, wheels, flight and cat poses", "Character::Drive / Animate"],
    ["world", "Room/house builders, story choreography, arrival, physical contacts", "BuildRoom / BuildHouse / StoryDirector"],
    ["render", "Raster shaders, shadow map, ray tracer, textures, debug geometry, HUD", "Renderer::Render / RayTracer::Render"],
    ["app", "Scene wiring, selection, input dispatch, mount/dismount and evidence export", "ToyRoomApp::StepScene / OnRender"],
])
h("3.2 Woody and Jessie: one humanoid construction", 2)
p("HumanoidStyle configures a reusable builder. A pelvis joint owns the torso, head, shoulders and hips; each shoulder owns the upper arm, elbow/forearm and hand, while each hip owns the thigh, knee/shin and boot. Ellipsoids model the head, hands and rounded details; cylinders model limbs; cubes provide the torso, garment panels and boots. Woody is identified by his brown hat, yellow plaid shirt, cow-print vest and denim trousers. Jessie changes the same structure to a red hat, white/red shirt, red hair braid and tan boots. Sharing materials and geometry keeps the construction consistent.")
f("woody", "Woody: hat, plaid shirt, cow-print vest, denim trousers and articulated limbs.")
p("Woody's silhouette comes from separately scaled hat brim, crown, torso and boots, rather than a single imported mesh. The plaid, cow-print and denim maps are selected per shape, so one shared primitive mesh can represent different garment surfaces. Shoulder and hip pivots rotate their descendants without changing the body root. His root position and heading are the quantities transferred to user control during live takeover.")
f("jessie", "Jessie: the same humanoid hierarchy with different garments, red hair, braid and hat.")
p('Jessie retains the same joint layout but changes the visible hat, hair, garment colours and boot proportions. The braid is assembled from rounded primitive sections under the head, so it follows head orientation. The saddle attachment changes the root parent while preserving the world transform; a seated pose then bends the existing legs. Dismounting restores an independent character root instead of duplicating the model.')
p("Drive computes the forward vector from heading, accelerates toward the requested speed and changes yaw with turn input. Animate advances the walk phase with travelled distance, not only wall-clock time. Opposite hips swing out of phase and shoulders swing against the legs. Motion blend approaches zero when the toy stops. Mounted Jessie blends to a seated pose and stops independent driving; selecting a mounted actor detaches Jessie for independent control. Voluntary remounting drives the connected pair.")
e("forward = (sin(heading),0,cos(heading))\nv += clamp(vTarget-v,-acceleration dt,+acceleration dt)\nheading += turnInput × turnRate × dt; position += forward × v × dt\nphase += v dt × 4; legSwing = sin(phase) × 35 degrees × moveBlend")
h("3.3 Bullseye and dynamic mounting", 2)
p("Bullseye uses an elongated sphere for the barrel, a separate neck/head hierarchy, muzzle, ears and eyes, four leg joints, hooves, mane, tail and a saddle. Differently scaled spheres preserve the horse's rounded toy silhouette. The saddle owns pad, flaps, straps, stirrups and an attachment joint. Gait animates the four leg joints and adds a small body bob; the saddle inherits that movement.")
f("bullseye", "Bullseye's ellipsoid body, articulated legs, muzzle, mane, tail and saddle.")
p("Mounting is accepted when Jessie's horizontal distance to Bullseye is no greater than 2.2 units and no transition is already running. The app remembers her world transform, reparents her root to the saddle and converts the placement into the saddle's coordinates. A 0.7-second interpolation takes her to the seat. Dismount converts back to a world-space position beside the horse and restores her independent collision body and controls. The placement conversion uses position and yaw; it is designed for the ordinary character rig rather than arbitrary affine reparenting of an externally sheared character.")
e("MlocalNew = inverse(MworldSaddle) MworldJessie\nMworldJessie = MworldBullseye MlocalSaddle MlocalJessie\nsmooth transition weight = q²(3-2q), q=clamp(elapsed/duration,0,1)")
f("mounted", "Jessie seated on Bullseye. The rider moves because her root is beneath the saddle in the scene graph.")
h("3.4 Buzz: flight, helmet and laser", 2)
p("Buzz extends the humanoid with a purple hood, clear spherical helmet, green/white armour, chest indicators, back pack, thrusters, wings and a wrist laser. The flight pose suppresses the walking gait, trails the legs, pitches the body according to cruise motion and banks while turning. A wings joint changes width between folded and extended poses. The helmet uses opacity 0.22; raster rendering blends it after opaque parts and ray tracing continues through its surface.")
f("buzz", "Buzz's armour, spherical helmet, wings and wrist-mounted laser emitter.")
p("L toggles the laser; Z/X changes its aim and Alt+click aims at a visible surface. The beam is a thin emissive cylinder whose transform follows the right-arm rig. A red point light at its tip supplies local glow. PhysicsWorld::FireLaser finds the nearest blocking hit and applies an impulse only if it is a dynamic wooden block. Furniture can intercept the beam before a hidden block. The beam length is shortened to the hit distance, linking the visible effect to the intersection result.")
f("laser", "Buzz's red beam strikes the block scene; the impulse moves and tumbles affected blocks.")
h("3.5 RC car: wheels, headlights and route", 2)
p("The car combines box chassis/body pieces, cabin, bumpers and grille with four cylinder wheels, hubs, axle details and an antenna. Wheel joints align cylinders with the axle and accumulate an angle equal to travelled distance divided by tyre radius. Two headlight anchors follow the car's world transform and emit forward/downward spotlights. L toggles manual headlights. During activation in the mission, headlights switch on and the car follows its route through the hallway into its home position.")
e("wheelAngle += travelledDistance / wheelRadius\nheadlightPosition = MworldAnchor[3].xyz\nheadlightDirection = normalize(anchor +Z axis + downward tilt)")
f("car", "The RC car in the connected hallway, with four wheels, body panels and headlight lenses.")
h("3.6 Penny: curved anatomy and the arrival", 2)
p("Penny is built from ellipsoids for the body, head, muzzle, cheeks and paws; pointed ears combine curved/triangular primitive forms, and the tail uses a separate curved arrangement of primitive sections. White material and ginger patch shapes identify the coat. Eye, nose, mouth and whisker details belong to the head hierarchy. Walking alternates the legs; sitting and sleeping reconfigure the existing rig. Head orientation follows the active toy during the mission.")
f("penny", "Penny's white coat, ginger patches, rounded head and seated pose on the bed.")
p("PennyArrival follows fifteen waypoints from the pavement through the gate, porch, ground-floor corridor, stairs and room. Each door is a child of a hinge joint and opens when Penny reaches the relevant part of the route. The stair flight has a 4.5-unit rise over an 8-unit run; the body pitch follows that slope. A 0.7-second eased interpolation with a sine lift produces the hop onto the bed. Route progress also drives sunset. The house exterior is hidden after the stairs are reached, and the downstairs interior is hidden after the arrival finishes.")
e("stairAngle = atan2(4.5,8) = 29.36 degrees\njumpPosition = mix(start,bed,q²(3-2q)) + (0,sin(pi q),0)\narrivalHour = 20.5 + 2.5 smoothstep(travelledDistance/routeLength)")
f("garden", "Penny's approach through the gate, porch and textured garden.")
f("stairs", "The arrival camera follows Penny through the ground-floor stair connection.")
h("3.7 Room shell, window and sky", 2)
p("The play room is 20 units wide, 18 deep and 7.5 high. Inward-facing wall planes are split around an actual back-wall window opening and right-wall doorway. Four window-frame strips, two mullions and a sill reveal an external sky plane, sun/moon spheres and distant house silhouettes. Side skirting and crown trim supply architectural edges. The window is an architectural opening; the implemented user-controlled opening is the door/lamp/character interaction system rather than a manually hinged window sash.")
f("window", "Window frame, curtain folds and the textured cratered moon visible through the wall opening.")
p("Environment::UpdateSky maps the 24-hour clock onto opposite sun and moon arcs. A smooth daylight factor blends ambient light, sky emission and directional-light colour. The emissive sun and moon are visible representations; a separate directional light represents illumination. The large sky plane is unlit and its star brightness fades during daytime.")
e("a = (hour-6) pi/12; sunHeight = sin(a)\nsunPosition = skyCentre + (-3.2 cos(a),3.1 sin(a),0)\nmoonPosition = orbit(a+pi); daylight = smoothstep(-0.1,0.25,sunHeight)")
h("3.8 Furnishings and texture-efficient detail", 2)
p("The desk uses a box top, four legs, drawer and a spherical brass knob. A sketchbook and three pencil cylinders sit on the top. The articulated lamp belongs to a separate root above the desk. The chair adds a seat, back and four legs. The bed uses frame, mattress, plaid blanket, headboard and two flattened-sphere pillows. The bookcase has uprights, back and four shelves; a single textured box on each shelf represents a row of book spines. Solid furniture contributes to collision bounds, while thin visual trim stays decorative.")
f("desk", "Desk, chair, lamp, sketchbook, pencils and drawer. Primitive construction leaves the structure easy to inspect.")
p('Desk and chair: box faces provide flat normals at the tabletop, drawer and leg edges; the brass knob uses a sphere with a stronger specular response. The three pencil cylinders and thin sketchbook remain decorative parts. Chair seat, back and four legs share the same wood material. Repeated wood UVs add grain without additional triangles, while solid furniture bounds keep driven characters outside the structure.')
f("bed", "Bed frame, mattress, orange plaid blanket, headboard, pillows and Penny.")
p('Bed: the frame and headboard establish the solid silhouette, while separate mattress and blanket boxes permit different surface materials. Two flattened spheres form soft pillows. The fabric pattern uses the existing face UVs and repeat scale, so the checked blanket is coloured surface detail. The bed also supplies the final arrival target for Penny; the jump and sleeping pose use her original rig.')
f("bookcase", "Four book rows are represented by textured boxes rather than many separately drawn books.")
p('Bookcase: uprights, backing and shelves are independent scaled boxes. Each shelf contains one textured book-row box; coloured spine bands suggest many books with fewer draw calls than individual book meshes. This is a deliberate surface-detail approximation. The frame retains geometric depth and cast-shadow structure, while the texture provides fine repetition that would otherwise require many small objects.')
p("A repeated fabric pattern covers eight curtain-fold cylinders. A wall poster is an independently UV-mapped plane. The rug uses concentric square colour bands on a plane just above the floor. Toy blocks are six cubes arranged as a tower; a larger doorway crate is a mission obstacle. Their star/bevel texture adds surface identity without adding bevel geometry. All leaf transforms and material assignments are recorded in objects.csv and the comprehensive construction notes; Appendix A indexes the complete scene groups.")
f("poster", "The room poster uses the custom BMP-loading path; the adjacent shelf uses procedural book-spine detail.")
p('Poster, curtains and rug: the poster is a plane with a single BMP image, giving a clear demonstration of file loading rather than procedural generation. Curtain folds use eight cylinders to produce an actual curved silhouette and changing normals. The rug is a slightly elevated plane with concentric colour bands. Small offsets prevent coincident surfaces from competing in the depth buffer.')
f("blocks", "The six-block tower and doorway crate. Boxes participate in gravity, separation and laser impulses.")
p('Blocks and doorway crate: each rigid box has its own translation and orientation, allowing gravity, separation and laser impulses to act independently. The star-and-border map identifies the faces, but its apparent bevel is a colour pattern rather than extra edge polygons. The crate is the story obstacle; the small tower provides a visible test of falling and tumbling objects after an impulse.')
h("3.9 Fan, clock and haunted props", 2)
p("The ceiling fan has a fixed mount and shaft, a spherical motor and four thin box blades. Each blade is placed below a rotor joint. The rotor turns at 110 degrees per second while world playback is active. The wall clock has a cylindrical rim and face, twelve box hour marks, two hand pivots and a central pin. Rotating each pivot moves the complete hand, and the two angles are derived from the scene hour rather than independent animation clocks.")
e("fanYaw = (fanYaw + 110 dt) mod 360\nhourHandAngle = -30 (hour mod 12) degrees\nminuteHandAngle = -360 fract(hour) degrees")
f("fan", "A four-blade ceiling fan: one animated parent carries all blades.")
f("clock", "The clock reads the same scene time used by the daylight cycle.")
p("The beach ball is one sphere below a position root, with six coloured UV gores and white polar regions. Rolling accumulates a Rodrigues rotation in its shape basis. The ghost combines a spherical head, conical sheet and dark face parts under a body joint. Its opacity fades toward night visibility; sinusoidal position, bobbing and body roll create floating motion. O toggles the haunted ambience outside edit mode, enabling autonomous ball motion, ghost appearance and lamp swivel/flicker without changing the coordinated story's default choreography.")
e("rollingAxis = normalize(up × displacement); rollingAngle = |displacement|/radius\nballBasisNext = R(rollingAxis,rollingAngle) ballBasis\nghostPosition = (4.5 sin(0.25t),4.2+0.35 sin(1.3t),3 cos(0.25t)-0.5)")
f("ball", "The ball's coloured gores use spherical UVs; its orientation accumulates from travelled distance.")
f("ghost", "A translucent, emissive ghost built from sphere and cone shapes with separate face details.")
h("3.10 Lamp hierarchy and moving illumination", 2)
p("The lamp has a cylinder base, arm pivot, cylinder arm, elbow sphere, head pivot, cone shade, emissive bulb sphere and a light anchor beyond the shade. A/D changes base yaw, W/S changes head tilt, R toggles power and comma/period adjust brightness. Both the point light and spotlight position follow the light anchor, while the spotlight direction is the head's transformed local -Y axis. Thus editing the lamp changes the light itself, not just the decorative mesh. In ambience mode, layered value noise modulates brightness and occasionally produces a short dropout.")
f("lamp", "The shade, bulb and hierarchy follow the lamp's controls, carrying the point and spot sources.")
h("3.11 House, doors and garden", 2)
p("BuildHouse constructs a two-storey facade, pitched roof, gables, trim, porch, garage and ground-floor corridor around the upper play room. A rotated, stretched cube supplies each gable silhouette; box sections form roof slopes. Siding, shingles and brick detail are tinted procedural maps. The porch has supports, railings and steps; transparent cutout picket maps replace repeated fence and railing geometry. The garden includes lawn, path, street, pavement, driveway, shrubs, five trees, flower details, mailbox and gate posts. The visible external sun contains an emissive core and translucent halo.")
f("house", "The full house exterior, porch, garage, fence, trees, lawn, pavement and street at the start of the arrival.")
p('Exterior groups: scaled boxes form the house walls, porch, garage and pavement, with roof and trim elements preserving the architectural outline. Fence pickets use alpha coverage to cut holes in a textured surface; their silhouette is not a separate mesh for every opening. Grass, siding, shingles and brick have distinct UV repeats. Trees and garden elements give depth to the arrival view and remain selectable or inspectable through their scene-node records.')
p("The front door, double toy-room door and stair door use hinge roots: yaw rotates the door and handle together. Arrival stage and Penny's proximity drive exponentially eased opening. Cinematic visibility hides downstairs geometry after arrival while retaining its inventory records. The shared texture array supplies exterior maps to both raster and ray-traced rendering.")

h("CHAPTER IV — Implementation, Results and Discussion")
h("4.1 Light sources and material response", 2)
t("Scene light configuration", ["Source", "Type / control", "Attenuation (kc,kl,kq)", "Cone / visibility"], [
    ["Sun / moon", "Directional; clock and F8", "(1,0,0) effective", "No cone; ray shadows"],
    ["Lamp bulb", "Point; lamp anchor, R power", "(1,0.14,0.07)", "All directions; ray shadows"],
    ["Lamp shade", "Spot; head -Y axis", "(1,0.05,0.01)", "22° / 34°; raster map + ray shadows"],
    ["Hall night light", "Point; fixed position", "(1,0.10,0.03)", "No general shadow test"],
    ["Left / right headlight", "Two spots; moving car, L", "(1,0.10,0.05)", "12° / 22°; no general shadow test"],
    ["Laser glow", "Point; Buzz laser tip, L", "(1,0.35,0.40)", "No general shadow test"],
    ["Ghost glow", "Point; ghost world position", "(1,0.30,0.15)", "Fades with ghost; no general shadow test"],
])
p("Eight light slots share one shader interface. Light intensity is refreshed each frame, so switching a lamp, activating the car or moving a glow source changes the actual illumination. Textures are multiplied into ambient/diffuse reflectance while highlights stay in light colour. Cloth uses low specular strength; brass and lamp metal use stronger, sharper highlights. The floor uses ks=0.35, shininess=48 and reflectivity=0.18; the ball uses ks=0.6, shininess=64 and reflectivity=0.12. Appendix B gives representative coefficients; materials.csv and the comprehensive notes give every material's actual coefficients.")
f("directional", "Directional contribution isolated with ambient disabled. Room walls can strongly limit the visible moonlight response in this view.")
f("point", "Lamp point-light contribution isolated; distance attenuation spreads a local pool near the bulb.")
f("spot", "Lamp spotlight isolated; the cone produces a directed pool and a depth-mapped shadow in raster mode.")
f("ambient", "Ambient-only image: material colours remain visible without directional surface response or highlights.")
f("diffuse", "Diffuse-only image: orientation, distance and spotlight coverage determine the light pattern.")
f("specular", "Specular-only image: concentrated highlights remain while the diffuse surface colour is suppressed.")
h("4.2 Matched shading comparison", 2)
p("The following images use the same camera, materials, time and light state. Only the raster shading mode changes. Wireframe and normal views identify the geometry behind the comparison. Gouraud's interpolated vertex light is usually less accurate around a small highlight; Phong computes the normal-based response per fragment. Flat makes individual planar facets easier to identify, while Blinn uses a half-vector term with four times the stored exponent.")
for name, caption in [("flat","Flat face-normal shading on Buzz."),("gouraud","Gouraud vertex illumination on the same model."),("phong","Phong per-fragment illumination with the reflection-vector highlight."),("blinn","Blinn-Phong half-vector illumination in the same view.")]: f(name,caption)
f("normals", "Vertex-normal debug lines on Buzz. The inverse-transpose normal matrix corrects non-uniformly scaled parts.")
h("4.3 Complete surface-map catalogue", 2)
p("The texture catalogue includes every sampled scene map and the white utility fallback. Native size, array layer, scene use and generation rule are listed alongside faithful exported images. The alpha fence map is also shown over a checker background to reveal holes; alpha is shape coverage and remains effective even when colour texturing is disabled. Texture rows in the exported inventory preserve the source dimensions.")
BLOCKS.append(("texture_catalogue",))
f("no-textures", "With colour textures disabled, flat material preview colours reveal the geometric construction. Cutout coverage still preserves fence holes.")
h("4.4 Raster and ray-traced results", 2)
p("The scene and camera remain the same in the following comparisons. Raster mode approximates curved geometry with triangles and uses the lamp shadow map; the ray tracer intersects exact primitive equations and can reveal off-screen geometry in the polished floor. Primary rays, shadow rays, mirror paths and opacity continuation are all implemented in the shader. Ray resolution defaults to half the display dimensions, giving one quarter of its pixels; minus/equal adjusts resolution from 0.2 to 1.0 and 9 cycles the bounce limit from zero to four.")
f("room-night", "Raster result with Blinn-Phong surface shading and the lamp's shadow map.")
f("ray-zero", "Ray-traced result with zero continuation bounces: analytic primary visibility and local illumination.")
f("room-ray", "Ray-traced result with two continuation bounces: reflections add a secondary view on the polished floor.")
f("house-ray", "Analytic ray tracing also renders the textured house exterior; the siding, roof and garden maps are sampled from the array.")
p("The shader uses quality thresholds to bound shadow work. Very weak light contributions are skipped; lights tagged for tracing cast an occlusion ray only when attenuation × intensity × max(N·L,0) exceeds 0.02. Transparent and unlit instances are excluded from general shadow occlusion. These choices improve interactive cost but mean visibility is deliberately approximate for weak lights and translucent objects. The tracer does not provide physical refraction or indirect diffuse illumination.")
h("4.5 Coordinated animation and interaction", 2)
t("Story states and visible graphics operations", ["Stage", "Action", "Graphics concept"], [
    ["Arrival", "Penny enters through doors, climbs and jumps to the bed", "Waypoints, hinges, camera following, slope/jump, sunset"],
    ["1 Discovery", "Woody looks toward the lost car", "Yaw steering and establishing camera"],
    ["2 Departure", "Jessie mounts; Buzz flies; Woody leads", "Hierarchy, pose blend, translation and flight"],
    ["3 Clear path", "Buzz's laser pushes the doorway obstacle", "Ray picking, impulse, emissive geometry"],
    ["4 Reach car", "The friends cross into the hallway", "Coordinated waypoint routes and contacts"],
    ["5 Activate car", "Enter or automatic activation starts its return", "User interaction, headlights, wheel rotation"],
    ["6 Return home", "Rider dismounts; toys return to their places", "World/local conversion and independent control"],
    ["7 Morning / End", "Lamp off, rest poses restored, Penny asleep", "Clock-driven lighting and complete pose restoration"],
])
p("The mission's transition guards test route completion, mounting state or laser impact. Enter explicitly activates the car in its activation scene; unattended playback performs that action after three seconds. Selecting a character during playback grants live ownership while the director continues other actors. The director never writes the owned actor's route, heading, special state or morning reset. A separate virtual route cursor advances at the scheduled speed, so a scene-completion guard cannot wait indefinitely for keyboard input. When Buzz is owned, the doorway opens after a three-second cinematic gate without changing his laser or aim. Scripted actors ignore the owned actor as a movement obstacle, while the owned actor retains furniture and wall contacts. Selecting a mounted rider or horse first detaches the rider for independent control; voluntarily remounting transfers the connected pair as one physical unit. Pressing 0 releases ownership and the actor steers from its current location toward the remaining route. N switches the complete scene to full manual mode or resumes story mode, Shift+N restarts the arrival and story, Y skips the arrival, and P pauses the story clock. The interface exposes the active rendering path and selected object. Penny can also be picked and driven after the arrival. A complete keyboard reference and a narration guide accompany the report.")
f("live-control", "Live takeover of Woody while Jessie and Buzz continue their scheduled departure. Input ownership changes one actor without pausing the scene clock.")
e("Owned route progress: delta = nextWaypoint - virtualPosition; d = length(delta)\nvirtualPositionNext = virtualPosition + delta min(d, routeSpeed dt)/d\nScene gate = virtual completion for owned actor AND real completion for other actors")
f("room-day", "The same room in daytime. The window, wall clock and material surfaces respond to the daylight setting.")
f("story-end", "The completed mission in morning light. All five driveable toys have returned and Penny is asleep.")
h("4.6 Collision and frame-time control", 2)
p("Moving actors and the camera use swept bounding boxes. Expanding an obstacle by the mover's half-size converts box movement into a segment/slab test. At contact the remaining motion loses its component into the contact normal, allowing sliding along furniture. Dynamic blocks use a fixed 1/120-second step with at most six steps per displayed frame. Gravity updates vertical speed, contact separation resolves overlaps and an impact transfers linear/angular velocity. This is a compact box approximation, not a full rigid-body constraint solver.")
e("vYNext = vY - 9.81 step; pNext = p + v step\nExpanded obstacle = [boxMin - moverHalf, boxMax + moverHalf]\nslideDelta = delta - n min(0,delta·n)\nMaximum physics work = 6 substeps × 1/120 s per frame")
h("4.7 Optimisation decisions", 2)
p("Geometry buffers and materials are shared. Sphere detail levels contain 1656, 396 or 100 triangles; cylinder and cone levels use 32, 16 or 8 sectors. Projected-size estimates choose detail levels. Raster frustum planes cull only shapes whose conservative bounds are outside the view. Opaque draws are grouped within depth slices by material and mesh; transparent shapes are sorted far-to-near and disable depth writes. Uniform locations are cached. The shadow pass skips inactive lamps and tiny/out-of-cone shapes. The ray tracer reuses CPU vectors and avoids per-item general 4 × 4 inversion by deriving inverse rows from the normal matrix. A single texture array prevents per-map sampler growth.")
e("LOD ratio = boundingRadius / distanceToEye\nratio < 0.012: low; ratio < 0.06: medium; otherwise full\nInverse affine row i = (normalMatrix column i, -dot(column i,translation))")
p("Cinematic visibility removes the exterior and downstairs geometry when the arrival no longer exposes them. Surface patterns replace book-spine and fence geometry where a colour/coverage map is sufficient. Fixed physics work prevents stalls from scheduling unbounded catch-up work. Deterministic media capture uses a fixed simulation step and raw RGB frame recording; the media generator validates frame count before encoding. Benchmark timings are execution observations, not a guarantee for every environment.")
BLOCKS.append(("benchmarks",))
h("4.8 Verification and achieved objectives", 2)
p("The final project is compiled in both Release and Debug configurations. The automated checks cover analytic intersections, normal perpendicularity, transform equivalence, shear-safe bounds, contact stability, laser impulse/occlusion, camera sliding and hallway access. The full arrival/mission replay reaches The End, logs mounting and dismounting, and restores the driveable toys to their expected home positions. Captures exercise all four raster shading modes, all three light types, term isolation, colour-texture toggling, analytic tracing, geometry debug views and object close-ups. The two-minute video is decoded after encoding to check media integrity.")
BLOCKS.append(("verification",))

h("Conclusions", 0)
p("The project implements the recorded toy-room concept as a complete interactive scene and coordinated animation. Its geometry, transforms, hierarchy, lighting, shading, texture generation and analytic ray tracing are exposed through controls and supported by actual rendered examples. A shared scene/material model connects the raster and ray-traced views, while resource reuse, level of detail, visibility culling, bounded simulation work and BVH traversal keep the implementation practical for demonstration. The complete node and material inventories make individual object construction traceable.")
p("The remaining design limits are specific: raster general shadows come from the lamp spotlight; ray shadows use selected sources and intensity thresholds; transparent rays continue straight; finite bounces close with local lighting; object interaction uses approximate boxes; and arbitrary affine edits are not a general-purpose rigging or reparenting system. Extensions could add refractive paths, broader shadow coverage or static/dynamic BVH separation, but these are separate enhancements to the implemented graphics scope.")

h("References", 0)
REFERENCES = [
    '[1] M. Segal and K. Akeley, The OpenGL Graphics System: A Specification, Version 3.3 Core Profile, Khronos Group, 2010. https://registry.khronos.org/OpenGL/specs/gl/glspec33.core.pdf',
    '[2] GLFW Project, GLFW 3.3 Documentation. https://www.glfw.org/docs/3.3/ (accessed Oct. 7, 2026).',
    '[3] B. T. Phong, “Illumination for computer generated pictures,” Communications of the ACM, vol. 18, no. 6, pp. 311–317, 1975, doi: 10.1145/360825.360839.',
    '[4] H. Gouraud, “Continuous shading of curved surfaces,” IEEE Transactions on Computers, vol. C-20, no. 6, pp. 623–629, 1971, doi: 10.1109/T-C.1971.223313.',
    '[5] J. F. Blinn, “Models of light reflection for computer synthesized pictures,” Proceedings of SIGGRAPH, pp. 192–198, 1977, doi: 10.1145/563858.563893.',
    '[6] T. Whitted, “An improved illumination model for shaded display,” Communications of the ACM, vol. 23, no. 6, pp. 343–349, 1980, doi: 10.1145/358876.358882.',
    '[7] M. Pharr, W. Jakob and G. Humphreys, Physically Based Rendering: From Theory to Implementation, 4th ed., “Bounding Volume Hierarchies,” 2023. https://www.pbr-book.org/4ed/Primitives_and_Intersection_Acceleration/Bounding_Volume_Hierarchies',
    '[8] G-Truc Creation, OpenGL Mathematics (GLM), source and documentation. https://github.com/g-truc/glm (accessed Oct. 7, 2026).',
    '[9] D. Herberth, GLAD OpenGL loader generator, source. https://github.com/Dav1dde/glad (accessed Oct. 7, 2026).',
    '[10] Pixar Animation Studios, Toy Story, 1995, and Toy Story 2, 1999. Visual character inspiration for the primitive-built toy cast. https://www.pixar.com/toy-story',
]
for ref in REFERENCES: p(ref)
p("The project uses the graphics concepts and public library interfaces cited above. Character names and recognisable colour/silhouette cues are inspired by Toy Story; the meshes are constructed locally from primitive builders rather than imported film assets. Scene screenshots are captured from the application, and explanatory diagrams are authored for this report. The poster is a locally generated image. The renderers, scene construction, procedural surface generators, BMP reader, object inspector and animation logic are project source implementations.")

TEXTURES = {
    "wood-floor": ("Floor, desk, chair, bed and fan blades", "Eight plank columns and staggered joints; per-plank hash tint, sinusoidal/noise grain and dark gaps."),
    "wallpaper": ("Room wall sections", "Two-tone vertical stripes and regularly placed diamond motifs in normalised UV space."),
    "rug": ("Floor rug", "Square radius d=max(|u-0.5|,|v-0.5|); band=floor(16d) mod 4 with fine value-noise variation."),
    "beach-ball": ("Rolling ball", "Longitude selects six colour gores; latitude creates white polar caps."),
    "toy-block": ("Tower blocks and doorway crate", "Face-border shading and a star motif imitate bevel/detail without extra triangles."),
    "poster": ("Wall poster", "24-bit BMP from the local poster generator; decoded by the project's BMP parser."),
    "night-sky": ("External sky backdrop", "Deterministic star locations on black; sky emission supplies the background and daylight fades stars."),
    "lunar-surface": ("Moon", "Procedural spherical crater/maria colour pattern with deterministic noise; no displacement mapping."),
    "woven-cotton": ("Shirts, curtains, horse mane/body", "Crossing fine periodic threads combined with low-amplitude noise."),
    "denim": ("Trousers and tyre detail", "Diagonal woven/twill modulation over the material's tint."),
    "worn-leather": ("Hats, boots and saddle", "Fine grain and uneven mottling from layered value noise."),
    "shirt-plaid": ("Shirts and orange blanket", "Two sets of periodic crossing stripe masks form checks; fabric noise adds small variation."),
    "cow-print": ("Woody's vest", "Thresholded smooth noise defines irregular dark patches on a light base."),
    "book-spines": ("Four bookcase rows", "Twelve UV cells, six-colour palette, hashed height, gap and gold title band."),
    "pickets": ("Fence and porch/stair rails", "Eight narrow pickets per repeat, triangular tips and two rails; alpha=0 in every hole."),
    "siding": ("House facade", "Eight board rows: fractional row height controls edge shading, with stretched wood noise."),
    "shingles": ("Roof slopes", "Eight staggered rows and six tabs per row; hashed tab brightness and dark gap masks."),
    "brick": ("House/porch masonry", "Eight running-bond courses, four bricks per row, half-brick row offsets and pale mortar masks."),
    "grass": ("Garden lawn", "Two noise scales: coarse clumps and fine elongated blade variation, tinted green."),
    "window-pane": ("Exterior windows", "Border/cross masks and a vertical glass gradient with a diagonal sheen; opaque colour map."),
    "flower-bed": ("Garden flower details", "Ten-by-ten hashed cells place blossom centres and choose among four colours over leaf noise."),
    "white": ("Untextured material fallback", "One white texel leaves the material's colour unchanged; no traced layer is required."),
}

from escape_content import revise
revise(BLOCKS, PROPOSAL, TEXTURES)
